### PR TITLE
Fix exist status handling

### LINKED ISSUE #69: Exist status is not passed back
the solc binary installed by svm does not pass back the exist status of the real solc, making it very difficult to deal with errors in build scripts.

### PR DESCRIPTION
**Pull request by moh-eulith**
Fixed #69

### CODE REVIEW

**Comment by moh-eulith** [comment]
Incidentally, it also fixes the terminal going wonky because the wrapper binary was not waiting for the child process.

**Review by mattsse — APPROVED** [review]
reasonable

**Comment by moh-eulith** [comment]
Is there something that needs to be changed in this PR?

**Comment by mattsse** [comment]
looks fine, friendly bump @roynalnaruto :)

**Review by roynalnaruto — APPROVED** [review]
Looks good :)

**Pull request merged**
