### PR TITLE
refactor: use BufWriter when writing solc bins

### PR DESCRIPTION
**Pull request by mattsse**

### CODE REVIEW

**Comment by roynalnaruto** [comment]
Hi @mattsse what are the benefits of using `io::BufWriter` over the existing implementation?

**Comment by mattsse** [comment]
hmm interesting, I thought the defacto standard was Bufwriter, but the rust nursery also uses io::copy

https://rust-lang-nursery.github.io/rust-cookbook/web/clients/download.html

this PR appears to be premature and does not really address https://github.com/gakonst/foundry/issues/442
the thing I actually want to fix, have to think about it a bit longer, therefor closing

**Comment by roynalnaruto** [comment]
Should we lock the file before we start writing the binary into it?

The `text file is busy` appears when the executable is accessed when it is being written into.

**Comment by mattsse** [comment]
yeah another idea I have is to write to some tmp dir then move to the dest location

**Comment by roynalnaruto** [comment]
I had initially planned on doing that (write to tmp and move). But I didn't do it since one of the previous changes (creating the file _just_ before copying the binary data to it) had fixed some flaky behaviour. Now that behaviour has re-appeared and so I think it'll be a good idea to write to tmp and then move once written (and see whether it fixes the flaky tests).

**Pull request closed without merging**
